---
title: "Predictive Analytics - Final Exam"
date: "13/06/2025"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  out.width = "60%",
  message = FALSE
)

library(tidyverse)
library(urca)
library(fpp3)
library(zoo)
library(strucchange)
library(patchwork)
library(fable)
library(fabletools)
```

## Data Loading and Exploration

```{r loading}
df1 <- read_csv("wikipedia_2007-2015_monthly.csv", show_col_types = FALSE) 
df2 <- read_csv("wikipedia_2016-2025_monthly.csv", show_col_types = FALSE)

#Excluding data after 2015, as this is covered by df2
df1 <- df1 %>%
  filter(as_date(month) < as_date("2016-01-01"))

# Excluding data after May 2025, as this is the newest data available at this time - this is for comparability if a newer dataset gets downloaded
df2 <- df2 %>%
  filter(as_date(month) < as_date("2025-06-01"))

views_raw <- bind_rows(df1, df2) %>%
  transmute(
    month = as_date(month),
    views = total.total,
    views_in_billions= total.total / 1e9
  ) %>%
  arrange(month)
```

```{r exploration}
glimpse(views_raw)
summary(views_raw)
plot1 <- views_raw %>% ggplot(aes(x = month, y = views_in_billions)) + geom_line()
ggsave("plot1.png", plot = plot1, dpi = 300)
plot1
```

```{r check_duplicates}
views_raw %>%
  count(month) %>%
  filter(n > 1)
```

```{r tsibble}
views_tsibble <- views_raw %>% 
  mutate(month = yearmonth(month)) %>%
  as_tsibble(index = month)

has_gaps(views_tsibble)
interval(views_tsibble)
```
```{r Spectral Entropy}
print(features(views_tsibble, .vars = views_tsibble$views, features = feat_spectral))
```




## Time Series Analysis

```{r plots}
# Seasonal plot
seasonal_plot <- views_tsibble %>% gg_season(views_in_billions) + ggtitle("Seasonality")

# Subseries plots (show month-to-month or weekday patterns)
subseries_plot <- views_tsibble %>% gg_subseries(views_in_billions) + ggtitle("Subseries")

# Rolling SD
sd_plot <- views_tsibble %>%
  mutate(rolling_sd = rollapply(views_in_billions, width = 12, FUN = sd, fill = NA)) %>%
  ggplot(aes(x = month, y = rolling_sd)) +
  geom_line() +
  ggtitle("Rolling Standard Deviation (12 months)")

ggsave("plot2.png", plot = seasonal_plot + subseries_plot + sd_plot, dpi = 300, width = 15, height = 5)
seasonal_plot
subseries_plot
sd_plot
```

## Mathematical Transformations

```{r log_transform}
views_tsibble <- views_tsibble %>%
  mutate(log_views = log(views))
log_plot <- views_tsibble %>%
  ggplot(aes(x = month, y = log_views)) +
  geom_line() +
  ggtitle("Log Transformation of Views")

log_sd_plot <- views_tsibble %>%
  mutate(rolling_sd = rollapply(log_views, width = 12, FUN = sd, fill = NA)) %>%
  ggplot(aes(x = month, y = rolling_sd)) +
  geom_line() +
  ggtitle("Rolling Standard Deviation (12 months) - Log Transformed")

ggsave("plot3.png", plot = log_plot+log_sd_plot, dpi = 300, width = 15, height = 7)
log_plot
log_sd_plot

```
```{r box_cox_transform}
guerrero_lambda <- views_tsibble %>%
  features(views_in_billions, guerrero) %>%
  pull(lambda_guerrero)
print(guerrero_lambda)
```
```{r box_cox_transform_plot}
views_tsibble <- views_tsibble %>%
  mutate(box_cox_views = box_cox(views_in_billions, lambda = guerrero_lambda))

box_cox_plot <- views_tsibble %>%
  ggplot(aes(x = month, y = box_cox_views)) +
  geom_line() +
  ggtitle("Box-Cox Transformation of Views")
box_cox_sd_plot <- views_tsibble %>%
  mutate(rolling_sd = rollapply(box_cox_views, width = 12, FUN = sd, fill = NA)) %>%
  ggplot(aes(x = month, y = rolling_sd)) +
  geom_line() +
  ggtitle("Rolling Standard Deviation (12 months) - Box-Cox")

ggsave("plot4.png", plot = box_cox_plot+box_cox_sd_plot, dpi = 300, width = 15, height = 7)
box_cox_plot
box_cox_sd_plot
```



## STL Decomposition

```{r STL Decomposition}
stl_plot <- views_tsibble %>%
  model(STL(box_cox_views ~ season(window = "periodic"), robust=TRUE)) %>%
  components() %>%
  autoplot() + ggtitle("STL Decomposition (Box-Cox transformed)")
ggsave("plot5.png", plot = stl_plot, dpi = 300, width = 10, height = 7)
stl_plot
```

```{r ACF PACF}

views_tsibble %>% ACF(views) %>% autoplot() + ggtitle("ACF")

views_tsibble %>% PACF(views) %>% autoplot() + ggtitle("PACF")
```

## Stationarity Tests
```{r stationarity_tests_function}
run_stationarity_tests <- function(data_ts, lags = 1, za=FALSE) {

  results <- list()

  # ADF Tests
  results$ADF_trend <- ur.df(data_ts, type = "trend", lags = lags)
  results$ADF_drift <- ur.df(data_ts, type = "drift", lags = lags)
    results$ADF_none  <- ur.df(data_ts, type = "none",  lags = lags)
    
  # KPSS Tests
    results$KPSS_trend <- ur.kpss(data_ts, type = "tau")
  results$KPSS_level <- ur.kpss(data_ts, type = "mu")

  # Zivot-Andrews Tests
  if (za){
  results$ZA_both <- ur.za(data_ts, model = "both",lag = lags)
  results$ZA_trend <-ur.za(data_ts, model = "trend",lag = lags)
  results$ZA_intercept <-ur.za(data_ts, model = "intercept",lag = lags)
  }
  # Output modes
  return(results)

}
``` 

```{r lag_selection}
views_ts <- as.ts(views_tsibble)
chosen_lag <- ar(views_ts[,4])$order
print(chosen_lag)
```
```{r stationarity}
stationarity_results <- run_stationarity_tests(views_ts[,4], lags = chosen_lag, za=TRUE)
lapply(stationarity_results, summary)
```

```{r differencing}
views_tsibble <- views_tsibble %>%
  mutate(
    diff_views = difference(views_in_billions, lag = 1),
    diff_log_views = difference(log_views, lag = 1),
    diff_box_cox_views = difference(box_cox_views, lag = 1)
  )

# Plot all 3 differenced series in 3 plots
views_tsibble %>%
  ggplot(aes(x = month, y = diff_views)) +
  geom_line() +
  ggtitle("Differenced Views")
views_tsibble %>%
  ggplot(aes(x = month, y = diff_log_views)) +
  geom_line() +
  ggtitle("Differenced Log Views")
box_cox_diff_plot <- views_tsibble %>%
  ggplot(aes(x = month, y = diff_box_cox_views)) +
  geom_line() +
  ggtitle("Differenced Box-Cox Views")

ggsave("plot6.png", plot = box_cox_diff_plot, dpi = 300)
box_cox_diff_plot
```

```{r stationarity_differenced}
views_ts <- as.ts(views_tsibble)
chosen_lag <- ar(views_ts[-1,7])$order
print(chosen_lag)
stationarity_results <- run_stationarity_tests(views_ts[-1,7], lags = chosen_lag, za=TRUE)
lapply(stationarity_results, summary)
```


## Structural Breaks Analysis

```{r Chow Test Naive Model}
views_tsi <- views_tsibble %>%
  mutate(
    Lag1 = lag(diff_box_cox_views)
  )

#locate the number of January 2016 to analyze as a possible break point
poss_break_point <- which(views_tsi$month == yearmonth("2016-01"))
print(poss_break_point)
chow_result <- sctest(formula = diff_box_cox_views ~ Lag1, type = "Chow", point = poss_break_point, data = as.ts(views_tsi))
print(chow_result)
```

```{r Auto ARIMA for Structural Breaks}
fit <- views_tsibble |>
  model(auto = ARIMA(diff_box_cox_views))
report(fit)
```


```{r QLR with AR Lags}
views_tsi <- views_tsi %>%
  mutate(
    Lag12 = lag(diff_box_cox_views, 12),  # Seasonal AR(1)
    Lag24 = lag(diff_box_cox_views, 24)   # Seasonal AR(2)
  )

chow_result2 <- sctest(diff_box_cox_views ~ 1 + Lag1 + Lag12 + Lag24, type = "Chow", point = poss_break_point, data = as.ts(views_tsi))
print(chow_result2)
```


```{r qlr_naive_model}
# Calculate F-statistics
qlr <- Fstats(diff_box_cox_views ~ Lag1, data = as.ts(views_tsi), from = 0.15)

# SupF test
print(sctest(qlr, type = "supF"))

# Estimate breakpoints
breaks <- breakpoints(qlr, alpha = 0.05)
print(breaks)

plot_fstats <- function(Fstats, breakpoints, title= "F-Statistics with Breakpoints") {
  plot(Fstats, alpha = 0.1, main = title)
  lines(breakpoints)
}

png("FStats_Naive.png")
plot_fstats(qlr, breaks, "F-Statistics Naive Model")
dev.off()

plot_fstats(qlr, breaks, "F-Statistics Naive Model")
```











```{r qlr_with_arima_lags}
qlr2 <- Fstats(diff_box_cox_views ~ 1 + Lag1 + Lag12 + Lag24, data = as.ts(views_tsi), from = 0.15)

# SupF test
print(sctest(qlr2, type = "supF"))

# Estimate breakpoints
breaks2 <- breakpoints(qlr2, alpha = 0.05)
print(breaks2)

png("FStats_ARIMA.png")
plot_fstats(qlr2, breaks2, "F-Statistics ARIMA Model")
dev.off()

plot_fstats(qlr2, breaks2, "F-Statistics ARIMA Model")
```


## Train Test Split

```{r train_test_split}
n_test <- floor(0.2 * nrow(views_tsibble))
train_data <- views_tsibble %>% slice_head(n = nrow(.) - n_test)
test_data  <- views_tsibble %>% slice_tail(n = n_test)
```

## Inital Modeling ARIMA

```{r model_selection}  
acf_pacf_plot <- views_tsibble %>%
  gg_tsdisplay(diff_box_cox_views, plot_type = "partial", lag_max=36)
ggsave("acf_pacf_plot.png", plot = acf_pacf_plot, dpi = 300, width = 10, height = 7)
acf_pacf_plot
```

Ideas: ARIMA(1,1,1)(1,1,1)[12]
ARIMA(0,1,1)(1,1,1)[12]
ARIMA(1,1,0)(1,1,1)[12]
ARIMA(2,1,1)(1,1,1)[12]
ARIMA(3,1,1)(1,1,1)[12]
ARIMA(4,1,1)(1,1,1)[12]

```{r Helper Functions}
report_models <- function(models, model_names=NULL) {
  if (is.null(model_names)) {
    model_names <- names(models)
  }
  
  for (model_name in model_names) {
    cat("====================\n")
    model_obj <- models[[model_name]][[1]]
    print(report(model_obj))

  }
}

test_ljung_box <- function(models, model_names = NULL, lag = 24) {
  if (is.null(model_names)) {
    model_names <- names(models)
  }
  
  results <- map(model_names, function(model_name) {
    model_obj <- models[[model_name]][[1]]
    
    ljung_box_result <- model_obj %>%
      augment() %>%
      features(.innov, ljung_box, lag = lag)
    
    info_criteria <- glance(model_obj) %>%
      select(AIC, AICc, BIC)

    bind_cols(
      tibble(model_name = model_name),
      info_criteria,
      ljung_box_result
    )
  })
  
  bind_rows(results)
}

plot_residuals <- function(models, model_names = NULL) {
  if (is.null(model_names)) {
    model_names <- names(models)
  }

  plots <- list()

  for (model_name in model_names) {
    plot <- models %>%
      select(model_name) %>%
      gg_tsresiduals() +
      ggtitle(paste("Residuals for", model_name))
    ggsave(paste0("residuals_", model_name, ".png"), plot = plot, dpi = 300, width = 10, height = 7)
    print(plot)

  }
}


```




```{r arima_ets_models}
  arima_full_specs <- list(
      arima_111 = ARIMA(box_cox(views_in_billions, lambda = guerrero_lambda) ~ 0 + pdq(1,1,1) + PDQ(1,0,1,            period = 12)),
      arima_110 = ARIMA(box_cox(views_in_billions, lambda = guerrero_lambda) ~ 0 + pdq(1,1,0) + PDQ(1,0,1,            period = 12)),
      arima_011 = ARIMA(box_cox(views_in_billions, lambda = guerrero_lambda) ~ 0 + pdq(0,1,1) + PDQ(1,0,1, period = 12)),
      arima_211 = ARIMA(box_cox(views_in_billions, lambda = guerrero_lambda) ~ 0 + pdq(2,1,1) + PDQ(1,0,1, period = 12)),
      arima_311 = ARIMA(box_cox(views_in_billions, lambda = guerrero_lambda) ~ 0 + pdq(3,1,1) + PDQ(1,0,1, period = 12)),
      arima_112 = ARIMA(box_cox(views_in_billions, lambda = guerrero_lambda) ~ 0 + pdq(1,1,2) + PDQ(1,0,1, period = 12)),
          arima_s001 = ARIMA(box_cox(views_in_billions, lambda = guerrero_lambda) ~ 0 + pdq(1,1,1) + PDQ(0,0,1, period = 12)),
          arima_s100 = ARIMA(box_cox(views_in_billions, lambda = guerrero_lambda) ~ 0 + pdq(1,1,1) + PDQ(1,0,0, period = 12)),
      auto_arima = ARIMA( box_cox(views_in_billions, lambda = guerrero_lambda), greedy = FALSE,
                          stepwise = FALSE, approximation = FALSE))

```

```{r Fit models}
arima_full_models <- train_data %>%
  model(!!!arima_full_specs)

arima_full_models %>%
  select(auto_arima) %>%
  report()
```

```{r Report Full Models}
report_models(arima_full_models)
```

```{r Ljung Box Test Full Models}
test_ljung_box(arima_full_models)
```

```{r Plot ARIMA Models}
plot_residuals(arima_full_models)
```





## Initial ETS Modeling

```{r}
ets_specs <- list(
    ets_A_A_A = ETS(box_cox(views_in_billions, lambda = guerrero_lambda) ~ error("A") + trend("A") + season("A")),
    ets_A_Ad_A = ETS(box_cox(views_in_billions, lambda = guerrero_lambda) ~ error("A") + trend("Ad") + season("A")),
    auto_ets   = ETS( box_cox(views_in_billions, lambda = guerrero_lambda)))
```

```{r Fit ETS Models}
ets_full_models <- train_data %>%
  model(!!!ets_specs)
ets_full_models %>%
  select(auto_ets) %>%
  report()
```

```{r Residual Plots ETS}
plot_residuals(ets_full_models)
```

```{r Report ETS Models}
report_models(ets_full_models)
```

```{r Ljung Box Test ETS}
test_ljung_box(ets_full_models)
```

```{r ETS Reduced Models}
ets_specs_reduced <- list(
    ets_A_A_A = ETS(box_cox(views_in_billions, lambda = guerrero_lambda) ~ error("A") + trend("A") + season("A")),
    auto_ets   = ETS(box_cox(views_in_billions, lambda = guerrero_lambda))
)
ets_reduced_models <- train_data %>%
  model(!!!ets_specs_reduced)
```

## Model Testing and Comparison

```{r Final Models}
final_model_specs <- list(
        arima_111 = ARIMA(box_cox(views_in_billions, lambda = guerrero_lambda) ~ 0 + pdq(1,1,1) + PDQ(1,0,1,            period = 12)),
    auto_arima = ARIMA(box_cox(views_in_billions, lambda = guerrero_lambda), greedy = FALSE,
                       stepwise = FALSE, approximation = FALSE),
    ets_A_A_A = ETS(box_cox(views_in_billions, lambda = guerrero_lambda) ~ error("A") + trend("A") + season("A")),
    auto_ets   = ETS(box_cox(views_in_billions, lambda = guerrero_lambda))
)
final_models <- train_data %>%
  model(!!!final_model_specs)

final_models %>%
  select(auto_arima) %>%
  report()

final_models %>%
  select(auto_ets) %>%
  report()
```



```{r Model Comparison}
test_prediction <- final_models %>%
  forecast(h = n_test)
accuracy(test_prediction, test_data)
```


```{r Plot CV Results}
plot7 <- autoplot(test_data, views_in_billions) +
  geom_line(data = test_prediction, aes(x =month, y = .mean, color = .model),
            alpha = 0.8) +
  labs(title = "Forecasts vs Actual Data",
       x = "Month", y = "Views in Billions",
       color = "Model")

ggsave("plot7.png",plot7, dpi = 300, width = 10, height = 7)
plot7
```

```{r Full Model with Confidence Intervals}
auto_arima_prediction <- test_prediction %>%
  filter(.model == "auto_arima")
plot8 <- autoplot(auto_arima_prediction, views_tsibble) +
  labs(title = "Forecast from Auto ARIMA",
       y = "Views (in billions)",
       x = "Time") 
ggsave("plot8.png", plot = plot8, dpi = 300, width = 10, height = 7)
plot8
```


```{r Full Model with Confidence Intervals}
ets_AAA_prediction <- test_prediction %>%
  filter(.model == "ets_A_A_A")
plot9<- autoplot(ets_AAA_prediction, views_tsibble) +
  labs(title = "Forecast from ETS(A,A,A)",
       y = "Views (in billions)",
       x = "Time") 
ggsave("plot9.png", plot = plot9, dpi = 300, width = 10, height = 7)
plot9
```


## Forecast of the Future

```{r Final Forecast}
final_fit <- views_tsibble %>%
  model( auto_arima  = ARIMA(box_cox(views_in_billions, lambda = guerrero_lambda) ~ 0 + pdq(1,1,1) + PDQ(2,0,2,            period = 12)))

final_fit %>%
  report()

final_forecast <- final_fit %>%
  forecast(h = "2 years")

plot10 <- autoplot(final_forecast, views_tsibble) +
  labs(title = "Final Forecast for Wikipedia Views",
       y = "Views (in billions)",
       x = "Time")
ggsave("plot10.png", plot10, dpi = 300, width = 10, height = 7)
plot10
```

